// Regenerates src/icons.js from the Phosphor icon set (regular weight).
// Run after changing the map below: node scripts/build-icons.js
// The output is committed, so the app does not read icon files at runtime.
const fs = require('fs');
const path = require('path');

// Site icon name -> Phosphor icon name. Keep the site names stable: categories
// store them in the database.
const MAP = {
  cpu: 'cpu', cog: 'gear-six', truck: 'bulldozer', car: 'car', sofa: 'couch', bricks: 'wall',
  grid: 'squares-four', droplet: 'bathtub', roof: 'house-line', door: 'door', bolt: 'lightning',
  sun: 'solar-panel', box: 'package', shirt: 't-shirt', tool: 'wrench', leaf: 'leaf', ship: 'boat',
  factory: 'factory', warehouse: 'warehouse', search: 'magnifying-glass', cart: 'shopping-cart-simple',
  user: 'user', check: 'check', shield: 'shield-check', chat: 'chat-circle-dots', menu: 'list',
  plus: 'plus', clipboard: 'clipboard-text', close: 'x', arrow: 'arrow-right', handshake: 'handshake',
  scan: 'scan', layers: 'stack', stamp: 'stamp', globe: 'globe-simple', container: 'shipping-container',
};

const dir = path.join(__dirname, '..', 'node_modules', '@phosphor-icons', 'core', 'assets', 'regular');
const lines = Object.entries(MAP).map(([name, file]) => {
  const svg = fs.readFileSync(path.join(dir, `${file}.svg`), 'utf8');
  const inner = svg.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/<rect width="256" height="256" fill="none"\/>/, '');
  return `  ${/^[a-z]+$/.test(name) ? name : `'${name}'`}: '${inner.replace(/'/g, "\\'")}',`;
});

const out = `// Inline SVG icons from Phosphor (regular weight, MIT licence).
// Generated by scripts/build-icons.js; edit the map there, not this file.
const PATHS = {
${lines.join('\n')}
};

function icon(name, size = 20, cls = '') {
  return \`<svg class="icon \${cls}" width="\${size}" height="\${size}" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true">\${PATHS[name] || PATHS.box}</svg>\`;
}

module.exports = { icon, ICON_NAMES: Object.keys(PATHS) };
`;
fs.writeFileSync(path.join(__dirname, '..', 'src', 'icons.js'), out);
console.log(`Wrote ${lines.length} icons to src/icons.js`);
